config/routes.rb
Rails.application.routes.draw do

  get '/root' => 'home#index', as: :root

  get 'experiment' => 'home#experiment', as: :experiment

  get "control_login" => 'control#login', as: :control_login
  
  post "validatecontroller" => 'control#validatecontroller', as: :validatecontroller

  match "control" => "control#index", via: [:get, :post]

  get "changetime" => 'control#changetime'

  get 'export_sample_csv' => 'control#export_sample_csv', as: :export_sample_csv

  get 'change_status' => 'control#change_status'

  get "participant" => 'participant#index'

  get "start_experiment" => 'control#start_experiment'

  get "stop_experiment" => 'control#stop_experiment'

  get "reset_experiment" => 'control#reset_experiment'

  post 'save_quiz_answers' => 'questions#save_quiz_answers', :as => :save_quiz_answers
   
  get 'quiz' => 'questions#index'
  
  get 'statements' => 'statements#index'
  
  get '/participant/sample_video' => 'participant#sample_video'
  
  post 'upload'=>'control#save_upload'
  
  get 'change_enable_status' => 'control#change_enable_status'
  
  get 'changelimit' => 'control#changelimit'
  
  get 'payments'=> 'payments#calculate'
  
  get 'results'=> 'payments#results'
  
  post '/participant/save' => 'participant#save'
  post '/participant/savedfilelocal' => 'participant#savedfilelocal'
  post '/participant/fileupload' => 'participant#fileupload'

  get 'get_participant_info'=> 'participant#get_information'
  
  post 'save_user_info'=>'participant#save_user_information'
  
  get '/getanswers'=> 'data#index'
  
  get '/getemotions'=> 'data#download_videos' 
  
  match 'control/pageupdate'=> 'control#pageupdate', via: [:get, :post]

  post 'control/autoplayenable' => 'control#autoplayenable'

  post 'control/autoplaydisable' => 'control#autoplaydisable'

  get '/calculate_round'=>'payments#calculate_round'
  
  get '/getstatements'=> 'data#download_statement_answers'
  
  get '/getpairing'=> 'data#get_pairing_details'
  
  get '/save_survey_details'=>'participant#save_survey_results'
  
  match 'participant/pageupdate'=> 'participant#pageupdate', via: [:get, :post]

  get '/getpayments'=>'data#download_payments'
  
  get '/getuserinfo'=>'data#download_userinfo'
  

end

app/controllers/questions_controller.rb
require "csv"
require "sinatra"
require "uuid"
class QuestionsController < ApplicationController
skip_before_action :verify_authenticity_token, :only => :upload
  def index
    @current_controller = controller_name
    @questions =  []
    csv_que = CSV::parse(File.open('public/master/questions.csv', 'r') {|f| f.read })
    fields = csv_que.shift
    @questions = csv_que.collect { |record| Hash[*fields.zip(record).flatten ] }
    @questions = @questions.group_by { |d| d["qid"].to_i }
    $user_data.select{|user| user[:computer_id] == "#{session[:computerid]}"}[0][:status]="Doing Quiz"
  end

  

  def save_quiz_answers
    ### save the quiz answer details
    ques_arr=[]
    answers= params.select{|key,val| key.include?("question")}
    ans_collection = [session[:computerid]] << answers.collect{|ans|ans[1]}
    (1 .. ans_collection.flatten.length - 1).each {|i|ques_arr << "Question_#{i}"}
    file = begin CSV.open("public/csv/quiz_answers_#{$filestamp}.csv", "r") rescue nil end
    if file
     CSV.open("public/csv/quiz_answers_#{$filestamp}.csv", "a+") do |csv|
      csv << ans_collection.flatten  
     end
    else
     CSV.open("public/csv/quiz_answers_#{$filestamp}.csv", "wb") do |csv|
     csv << ["Part ID",ques_arr].flatten
     csv << ans_collection.flatten
    end
    end
    ### save the quiz answer details
    ### perform pairing
    computer_ids= $user_data.collect{|data|data[:computer_id] if data[:computer_id]!="nil"}.shuffle.compact
    $paired_users=computer_ids.each_slice(2).to_a if $paired_users.empty?
    pairing_file = begin CSV.open("public/csv/pairing_details_#{$filestamp}.csv", "r") rescue nil end
    if !pairing_file
      CSV.open("public/csv/pairing_details_#{$filestamp}.csv", "wb") do |csv|
       $paired_users.each do |pair|
         csv << pair  
       end
      end
    end
   
    ###
   $user_data.select{|user| user[:computer_id] == "#{session[:computerid]}"}[0][:status]="Completed Quiz And Waiting"
   redirect_to participant_path(:from=>"quiz")
   # redirect_to statements_path
  end


  def upload
    uuid = UUID.generate
    
    puts params.inspect


    audio_type = params['audio'].content_type.split("/").last

    File.open("public/uploads/#{uuid}.#{audio_type}", "w") { |f| f.write(File.read(params['audio'].tempfile)) }

    video_type = params['video'].content_type.split("/").last


File.open("public/uploads/#{uuid}.#{video_type}", "w") { |f| f.write(File.read(params['video'].tempfile)) }

    
    `ffmpeg -i public/uploads/#{uuid}.webm public/uploads/#{uuid}.mp4`
    `ffmpeg -i public/uploads/#{uuid}.mp4 -i public/uploads/#{uuid}.wav -c:v copy -c:a aac -strict experimental public/videos/#{uuid}.mp4`

    uuid
  end

end

app/views/questions/index.html.erb
<div align="center">
	<h3>Quiz</h3>
</div>
<%= form_tag(save_quiz_answers_path, :id => "quizform", :method => "POST") do %>
<section class="demo">
	<div class="container">
		<%@questions.each do |question|%>
		<% ques = question[1].select {|n| n["ref"].to_i == 0 } %>
		<% options = question[1].select {|n| n["ref"].to_i != 0 } %>
		<div>
			<p>
			</p>
			<h3 align="left"><b><%= ques[0]["data"] %></b></h3>
			<ul class="que-ans">
			<% options.each do |opt| %>
				<li>
					<h3><%= radio_button_tag("question_#{opt['qid']}", opt["ref"].to_i,checked =false, :class=>'question-label') %><%= label_tag(opt["qid"], opt["data"],:class=>'ans-label') %></h3>
				</li>
			
			<% end %>
			</ul>
		</div>
		<% end %>
	</div>
</section>
 <button class="next" type="button">Next</button>
  <div class="save_button">
    <%= submit_tag "Next", :id => "submitbutton" %>
  </div>
<% end %>
<%= render :partial => "shared/controllerinfo" %>

<script type="text/javascript">
var currentIndex = 0;
items = $('.container div');
itemAmt = items.length;
$('.save_button').hide();
</script>

<style>
input[type="submit"],.next {
border-radius: 5px;
border: 0;
width: 100px;
height:40px;
width: 100px;
height: 40px;
color: green;
/*#margin-top: 28px;
#margin-left: 551px;*/
margin: 1% 45%
}
</style>