config/routes.rb
Rails.application.routes.draw do

  get '/root' => 'home#index', as: :root

  get 'experiment' => 'home#experiment', as: :experiment

  get "control_login" => 'control#login', as: :control_login
  
  post "validatecontroller" => 'control#validatecontroller', as: :validatecontroller

  match "control" => "control#index", via: [:get, :post]

  get "changetime" => 'control#changetime'

  get 'export_sample_csv' => 'control#export_sample_csv', as: :export_sample_csv

  get 'change_status' => 'control#change_status'

  get "participant" => 'participant#index'

  get "start_experiment" => 'control#start_experiment'

  get "stop_experiment" => 'control#stop_experiment'

  get "reset_experiment" => 'control#reset_experiment'

  post 'save_quiz_answers' => 'questions#save_quiz_answers', :as => :save_quiz_answers
   
  get 'quiz' => 'questions#index'
  
  get 'statements' => 'statements#index'
  
  get '/participant/sample_video' => 'participant#sample_video'
  
  post 'upload'=>'control#save_upload'
  
  get 'change_enable_status' => 'control#change_enable_status'
  
  get 'changelimit' => 'control#changelimit'
  
  get 'payments'=> 'payments#calculate'
  
  get 'results'=> 'payments#results'
  
  post '/participant/save' => 'participant#save'
  post '/participant/savedfilelocal' => 'participant#savedfilelocal'
  post '/participant/fileupload' => 'participant#fileupload'

  get 'get_participant_info'=> 'participant#get_information'
  
  post 'save_user_info'=>'participant#save_user_information'
  
  get '/getanswers'=> 'data#index'
  
  get '/getemotions'=> 'data#download_videos' 
  
  match 'control/pageupdate'=> 'control#pageupdate', via: [:get, :post]

  post 'control/autoplayenable' => 'control#autoplayenable'

  post 'control/autoplaydisable' => 'control#autoplaydisable'

  get '/calculate_round'=>'payments#calculate_round'
  
  get '/getstatements'=> 'data#download_statement_answers'
  
  get '/getpairing'=> 'data#get_pairing_details'
  
  get '/save_survey_details'=>'participant#save_survey_results'
  
  match 'participant/pageupdate'=> 'participant#pageupdate', via: [:get, :post]

  get '/getpayments'=>'data#download_payments'
  
  get '/getuserinfo'=>'data#download_userinfo'
  

end

app/controllers/control_controller.rb
require 'csv'
class ControlController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  #before_filter :check_valid_control, :except => [:login, :validatecontroller]
  respond_to :html, :js, :json
  
  def index
    @current_controller = controller_name
    respond_to do|format|
			#format.js
      format.html
      format.json
		end
  end

  def login
    
  end

  def validatecontroller
    if params[:control_login].present? and  params[:control_password].present?
      if params[:control_login] == $control_id and params[:control_password] == $control_password
        $valid_control = true
        redirect_to control_path
      else
        redirect_to control_login_path
      end
    else
      redirect_to control_login_path
    end
  end

  def changetime
    newtime = params[:time].to_i
    $gConfigData.newtime(newtime.to_i)
    render json:{time: $gConfigData.time},status: :ok
  end


  def export_sample_csv
    csv_string = CSV.generate do |csv|
      csv << ["qid", "ref", "data", "answer"]
    end
    send_data csv_string,
      :type => 'text/csv',
      :filename => 'questions.csv',
      :disposition => 'attachment'
  end


  def change_status
    computer_id  = params[:computer_id]
    $user_data.select do |user|
      if user[:computer_id] == computer_id
        user[:connection] = "active"
      end
    end
    render json:{},status: :ok
  end


  def start_experiment
    $experiment_status = params[:status]
    if ["stop","reset"].include?(params[:status])
      session[:status] = nil
      $user_data.each do |user|
       user[:connection]="disabled"
      end
    end
    if $experiment_status=="start"
      $round=1
      $recording_count=0
      $feedback_recording=0
      session[$round]=nil
      $filestamp = Time.now.strftime("%Y-%m-%d-%H-%M")
      Rails.logger.info("$filestamp = #{$filestamp}")

    elsif $experiment_status=="reset"
      $user_count = 0
      $round=0
      $user_data.each do |user|
        user[0][:computer_id]=nil
        user[0][:status]="online"
      end
      reset_session
    end
    render json:{},status: :ok
  end
  
  def save_upload
    if params[:upload]
    name = params[:upload][:file].original_filename
    directory = "public/master"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    else
      flash[:notice] = "Please select a file to upload!!"
    end
    redirect_to control_path
  end
  
  def change_enable_status
    if params["status"] == "enable"
      $user_data.select do |user|
        user[:connection] = "enabled"
      end      
      session[:status]= nil
    end
    render json:{},status: :ok
  end
  
  def changelimit
    newlimit = params[:limit].to_i
    $limit = $gUserLimitData.newlimit(newlimit.to_i)
    $partcount = newlimit.to_i
    render json:{limit: $gUserLimitData.limit},status: :ok
  end
  
  def pageupdate
    @userdata= $user_data
    render :layout=>false
  end

  def autoplayenable
    $Autoplay = "true"
    render nothing: true
  end
  def autoplaydisable
    $Autoplay = "false"
    render nothing: true
  end

  
end

app/helpers/control_helper.rb
module ControlHelper
end

app/views/control/_popup.html.erb
<div class="modal fade" id="quizdata" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Basic Modal</h4>
      </div>
      <div class="modal-body">
        <h3>Modal Body</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



<style>
  h2 {
  text-align: center;
}

.p {
  text-align: center;
  padding-top: 130px;
}
</style>

app/views/control/index.html.erb
<div class="container-fluid">
	<br>
	<div class="row">
		<div class="col-md-3" id="side-content">
			<div class="table-responsive table-bordered table-hover">
				<table class="table">
					<thead>
						<tr>
							<th>Participant</th>
							<th>Computer ID</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody>
						<% $user_data.each do |row| %>
						<tr class="users">
							<td><%= row[:id] %></td>
							<%=hidden_field 'user','count',:value=>$user_count%>
							<td><%= row[:computer_id] %></td>
							<td><%= row[:status] %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-md-9" id="main-content">
			<div class="row">
				<div class="col-md-4">
					<ul>
						<li>
							<div id="timevalue">
								&nbsp;
							</div>
							<input id="timebutton" type="button" value="Change Duration" />
						</li>
						<li>
							<div id="userlimit">
								<div id="uservalue">
									&nbsp;
								</div>
								<input id="userlimitbutton" type="button" value="Change Limit" />
								</td>
						</li>
					</ul>
					<ul>
						<li>
							<input id="enable" type="button" title="Enable connections for all the users" value="Enable Connections" onclick="enable_users('enable')" />
						</li>
						<li>
							<input id="start" type="button" title="Click to start experiment once the connection is set" value="Start Experiment" onclick="change_experiment_status('start')" />
						</li>
						<li>
							<input id="stop" type="button" title="Click to stop experiment" value="Stop Experiment" onclick="change_experiment_status('stop')" />
						</li>
						<li>
							<input id="reset" type="button" title="Click to reset experiment" value="Reset Experiment" onclick="change_experiment_status('reset')" />
						</li>
					</ul>
					<ul>
						<li>
							<input id="downloadanswers" type="button" value="Download Answers" />
						</li>
						<li>
							<input id="downloademotions" type="button" value="Download Emotions" />
						</li>
						<li>
							<input id="watchpairing" type="button" value="See Pairing" />
						</li>
						<li>
							<input id="downloadstatements" type="button" value="Statement and Survey Results" />
						</li>
						<li>
							<input id="downloadpayments" type="button" value="Download Payments" />
						</li>
						<li>
							<input id="downloaduserinfo" type="button" value="Download User info" />
						</li>
					</ul>
				</div>
				<div class="col-md-8" id="upload-content">
					<h2>Upload Your Questions Here!</h2>
					<%= form_tag 'upload', { :multipart => true } do %>
					<p>
						<%= file_field_tag 'upload[file]' %>
					</p>
					<p id="submit">
						<%= submit_tag "Upload" %>
					</p>
					<% end %></br>
					<h5><a href="<%=export_sample_csv_path%>">click here </a><b>to download sample questions file</b></h5>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="autoplaybox">
  <div id="autoplaylabel">AutoPlay:</div>
  <div id="autoplayvalue">Disabled</div>
  <input id="autoplaybutton" type="button" value="Change AutoPlay" />
</div>
<%= render :partial => "shared/controllerinfo" %>

<script type="text/javascript">
    $((function () {
        $("#timevalue").html("<b>Time:- </b><span id=timecount>" + <%= $gConfigData.time %>+"</span>");
        $("#timebutton").click(function(){
        var currentvalue = $("#timecount").html();
        var answer = prompt("Enter new time",currentvalue);
        if(answer != null){
         answer = jQuery.trim(answer);
         if(answer != currentvalue){
           changetime(answer);
          }
         }
      });
     })
   );
$("#uservalue").html("<b>No of users:- </b><span id=usercount>" + <%= $gUserLimitData.limit.nil? ? 2 : $gUserLimitData.limit%>
	+"</span>");
	$((function() {
		$("#userlimitbutton").click(function() {
			var currentvalue = $("#usercount").html();
			var answer = prompt("Enter new Value", currentvalue);
			answer = jQuery.trim(answer);
			if (answer != '' && answer <= 24 && answer >= 0 && (answer % 2) ==0) {
				if (answer != currentvalue) {
					changeuserlimits(answer);
				}
			} else {
				if (answer!=''){
				alert("Please enter Valid even number.. i.e 1 to 24")
				}
			}
		});
	}));
	function changetime(newtime) {
		var time = newtime;
		values = "time=" + time;
		$.ajax({
			url : "/changetime",
			data : values,
			type : 'get',
			success : function(html) {
				$("#timevalue").html("<b>Time:- </b><span id=timecount>" + newtime + "</span>");
			}
		});
	}

	function changeuserlimits(newlimit) {
		var limit = newlimit;
		values = "limit=" + limit;
		$.ajax({
			url : "/changelimit",
			data : values,
			type : 'get',
			success : function(html) {
				$("#uservalue").html("<b>No of users:- </b><span id=usercount>" + newlimit + "</span>");
				//if (newlimit == $("#user_limit").val()) {
				//	$("#enable").removeAttr("disabled");
				//}
			}
		});
	}
</script>
<style>
input[type="submit"] {
border-radius: 5px;
border: 0;
width: 100px;
height:40px;
width: 100px;
height: 40px;
color: green;
margin-top: 28px;
margin-left: 1px;
}
</style>

app/views/control/index.js.erb
$("#control_dashboard").html("<%= escape_javascript(render(:partial => 'control/users'))%>");

app/views/control/pageupdate.html.erb
 <table class="users_table">
        <tr>
          <th>Participant</th></br>
          <th>Computer ID</th>
          <th>Status</th>
        </tr>
        <% @userdata.each do |row| %>
          <tr class="users">
            <td><%= row[:id] %></td>
            <td><%= row[:computer_id] %></td>
            <td><%= row[:status] %></td>
          </tr>
        <% end %>
      </table>